/** All Bible versions supported by BibleGateway, used as the master list. */
export const BIBLE_VERSIONS = [
  { code: "KJ21", name: "21st Century King James Version" },
  { code: "ASV", name: "American Standard Version" },
  { code: "AMP", name: "Amplified Bible" },
  { code: "AMPC", name: "Amplified Bible, Classic Edition" },
  { code: "BRG", name: "BRG Bible" },
  { code: "CSB", name: "Christian Standard Bible" },
  { code: "CSBA", name: "Christian Standard Bible Anglicised" },
  { code: "CEB", name: "Common English Bible" },
  { code: "CJB", name: "Complete Jewish Bible" },
  { code: "CEV", name: "Contemporary English Version" },
  { code: "DARBY", name: "Darby Translation" },
  { code: "DLNT", name: "Disciples' Literal New Testament" },
  { code: "DRA", name: "Douay-Rheims 1899 American Edition" },
  { code: "ERV", name: "Easy-to-Read Version" },
  { code: "EASY", name: "EasyEnglish Bible" },
  { code: "EHV", name: "Evangelical Heritage Version" },
  { code: "ESV", name: "English Standard Version" },
  { code: "ESVUK", name: "English Standard Version Anglicised" },
  { code: "EXB", name: "Expanded Bible" },
  { code: "GNV", name: "1599 Geneva Bible" },
  { code: "GW", name: "GOD'S WORD Translation" },
  { code: "GNT", name: "Good News Translation" },
  { code: "HCSB", name: "Holman Christian Standard Bible" },
  { code: "ICB", name: "International Children's Bible" },
  { code: "ISV", name: "International Standard Version" },
  { code: "PHILLIPS", name: "J.B. Phillips New Testament" },
  { code: "JUB", name: "Jubilee Bible 2000" },
  { code: "KJV", name: "King James Version" },
  { code: "AKJV", name: "Authorized (King James) Version" },
  { code: "LSB", name: "Legacy Standard Bible" },
  { code: "LEB", name: "Lexham English Bible" },
  { code: "TLB", name: "Living Bible" },
  { code: "MSG", name: "The Message" },
  { code: "MEV", name: "Modern English Version" },
  { code: "MOUNCE", name: "Mounce Reverse Interlinear New Testament" },
  { code: "NOG", name: "Names of God Bible" },
  { code: "NABRE", name: "New American Bible (Revised Edition)" },
  { code: "NASB", name: "New American Standard Bible" },
  { code: "NASB1995", name: "New American Standard Bible 1995" },
  { code: "NCB", name: "New Catholic Bible" },
  { code: "NCV", name: "New Century Version" },
  { code: "NET", name: "New English Translation" },
  { code: "NIRV", name: "New International Reader's Version" },
  { code: "NIV", name: "New International Version" },
  { code: "NIVUK", name: "New International Version - UK" },
  { code: "NKJV", name: "New King James Version" },
  { code: "NLV", name: "New Life Version" },
  { code: "NLT", name: "New Living Translation" },
  { code: "NMB", name: "New Matthew Bible" },
  { code: "NRSVA", name: "New Revised Standard Version, Anglicised" },
  { code: "NRSVACE", name: "NRSV Anglicised Catholic Edition" },
  { code: "NRSVCE", name: "NRSV Catholic Edition" },
  { code: "NRSVUE", name: "NRSV Updated Edition" },
  { code: "NTFE", name: "New Testament for Everyone" },
  { code: "OJB", name: "Orthodox Jewish Bible" },
  { code: "RGT", name: "Revised Geneva Translation" },
  { code: "RSV", name: "Revised Standard Version" },
  { code: "RSVCE", name: "Revised Standard Version Catholic Edition" },
  { code: "TLV", name: "Tree of Life Version" },
  { code: "VOICE", name: "The Voice" },
  { code: "WEB", name: "World English Bible" },
  { code: "WE", name: "Worldwide English (New Testament)" },
  { code: "WYC", name: "Wycliffe Bible" },
  { code: "YLT", name: "Young's Literal Translation" },
] as const;

/** Map BibleGateway version codes to wldeh/bible-api folder IDs for verse preview. */
export const VERSION_TO_BIBLE_API: Record<string, string> = {
  KJV: "en-kjv",
  AKJV: "en-kjv",
  ASV: "en-asv",
  BSB: "en-bsb",
  DRA: "en-dra",
  GNV: "en-gnv",
  LSV: "en-lsv",
  WEB: "en-web",
};

export const BIBLE_API_DEFAULT = VERSION_TO_BIBLE_API.BSB;
