// Database types - will be generated by Supabase CLI
// For now, define manually based on our schema

export type UserRole = "USER" | "ADMIN";
export type PreferredLanguage = "en" | "ja";
export type ClipStatus = "PENDING" | "APPROVED" | "REJECTED";

export interface User {
  id: string;
  display_name: string | null;
  preferred_language: PreferredLanguage;
  role: UserRole;
  created_at: string;
  updated_at: string;
}

export interface Clip {
  id: string;
  youtube_video_id: string;
  start_time: number;
  end_time: number;
  title: string;
  title_ja: string | null;
  description: string | null;
  description_ja: string | null;
  submitted_by: string;
  approved_by: string | null;
  status: ClipStatus;
  is_featured: boolean;
  vote_count: number;
  created_at: string;
  updated_at: string;
}

export interface ClipVerse {
  id: string;
  clip_id: string;
  book: string;
  book_ja: string;
  chapter: number;
  verse_start: number;
  verse_end: number | null;
}

export interface Category {
  id: string;
  slug: string;
  name_en: string;
  name_ja: string;
  sort_order: number;
  created_at: string;
}

export interface ClipCategory {
  clip_id: string;
  category_id: string;
}

export interface Vote {
  user_id: string;
  clip_id: string;
  created_at: string;
}

export type CommentReportReason = 'spam' | 'harassment' | 'inappropriate' | 'other';
export type CommentReportStatus = 'PENDING' | 'REVIEWED' | 'DISMISSED';

export interface Comment {
  id: string;
  clip_id: string;
  user_id: string;
  content: string;
  like_count: number;
  created_at: string;
  updated_at: string;
}

export interface CommentLike {
  comment_id: string;
  user_id: string;
  created_at: string;
}

export interface CommentReport {
  id: string;
  comment_id: string;
  user_id: string;
  reason: CommentReportReason;
  description: string | null;
  status: CommentReportStatus;
  created_at: string;
}

export interface CommentWithUser extends Comment {
  user: Pick<User, 'id' | 'display_name'> | null;
}

export interface ClipSubtitle {
  id: string;
  clip_id: string;
  word: string;
  start_time: number; // seconds from video start
  end_time: number;   // seconds from video start
  sequence: number;   // word order (0, 1, 2, ...)
  created_at: string;
}

// Query result types
export interface ClipWithRelations extends Clip {
  verses: ClipVerse[];
  categories: Category[];
  submitted_by_user: User | null;
}
